name = "splat"
compatibility_date = "2026-02-17"
workers_dev = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[routes]]
pattern = "splatterboard.app"
custom_domain = true

[[routes]]
pattern = "www.splatterboard.app"
custom_domain = true
